[package]
name = "grep-clone"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A mini grep clone from the Rust-lang official tutorial"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
